context:
  version: "0.1.1"
  python_min: "3.12"

package:
  name: adsorption
  version: ${{ version }}

source:
  url: https://github.com/LiuGaoyong/Adsorption/releases/download/v${{ version }}/adsorption-${{ version }}.tar.gz
  sha256: f1be0f8901e1fd2f7c18413534d473792a5c14a05d584fb1c732bb0100336881

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - array-api-compat
    - ase
    - graphatoms >=1.1
    - hydra-core >=1.1
    - ray-default >=2.50
    - ray-tune >=2.50
    - typing-extensions

tests:
  - python:
      imports:
        - adsorption
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/LiuGaoyong/Adsorption
  summary: The Python package for the adsorption of molecules on clusters or surfaces.
  description: |
    The Python package for the adsorption of molecules on clusters or surfaces.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/LiuGaoyong/Adsorption

extra:
  recipe-maintainers:
    - LiuGaoyong
